version: '2.1'

services:
  expense-tracker:
    image: expense-tracker
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js